Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ankan\AppData\Local\Temp\ipykernel_32684\555797462.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 65, in <module>
    from pandas.core import (
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 23, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\ankan\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
    self.io_loop.start()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "c:\Users\ankan\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
    res = shell.run_cell(
  File "c:\Users\ankan\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
    result = self._run_cell(
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
    result = runner(coro)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\ankan\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ankan\AppData\Local\Temp\ipykernel_32684\555797462.py", line 1, in <module>
    import pandas as pd
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 56, in <module>
    from pandas.core import (
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "c:\Users\ankan\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\ankan\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\ankan\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

Load The Dataset

In [ ]:
forest_sheets = pd.read_excel(r"Bird_Monitoring_Data_FOREST.XLSX", sheet_name=None)
grassland_sheets = pd.read_excel(r"Bird_Monitoring_Data_GRASSLAND.XLSX", sheet_name=None)

In [3]:
# combine the sheets
forest=pd.concat(forest_sheets.values(),ignore_index=True)
grassland=pd.concat(grassland_sheets.values(),ignore_index=True)
print(forest.shape)
print(grassland.shape)

(8546, 29)
(8531, 29)

In [4]:
# Rename Column
grassland.rename(columns={'TaxonCode':'NPSTaxonCode'},inplace=True)

In [5]:
forest["Habitat"] = "Forest"
grassland["Habitat"] = "Grassland"

In [6]:
# Merge this Two Dataset
df = pd.concat([forest, grassland],ignore_index=True,sort=False)
df

,Admin_Unit_Code,Sub_Unit_Code,Site_Name,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,...,PIF_Watchlist_Status,Regional_Stewardship_Status,Temperature,Humidity,Sky,Wind,Disturbance,Initial_Three_Min_Cnt,Habitat,Previously_Obs
0,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22 00:00:00,06:19:00,06:29:00,Elizabeth Oswald,...,False,True,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,Forest,NaN
1,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22 00:00:00,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,True,Forest,NaN
2,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22 00:00:00,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,Forest,NaN
3,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22 00:00:00,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,Forest,NaN
4,ANTI,NaN,ANTI 1,ANTI-0036,Forest,2018,2018-05-22 00:00:00,06:19:00,06:29:00,Elizabeth Oswald,...,False,False,19.9,79.400002,Cloudy/Overcast,Calm (< 1 mph) smoke rises vertically,No effect on count,False,Forest,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17072,MONO,NaN,NaN,MONO-0089,Grassland,2018,2018-05-10 00:00:00,06:35:00,06:46:00,Brian Swimelar,...,False,False,19.0,63.0,Partly Cloudy,Light air movement (1-3 mph) smoke drifts,Slight effect on count,False,Grassland,False
17073,MONO,NaN,NaN,MONO-0089,Grassland,2018,2018-05-10 00:00:00,06:35:00,06:46:00,Brian Swimelar,...,False,False,19.0,63.0,Partly Cloudy,Light air movement (1-3 mph) smoke drifts,Slight effect on count,False,Grassland,False
17074,MONO,NaN,NaN,MONO-0089,Grassland,2018,2018-05-10 00:00:00,06:35:00,06:46:00,Brian Swimelar,...,False,False,19.0,63.0,Partly Cloudy,Light air movement (1-3 mph) smoke drifts,Slight effect on count,False,Grassland,False
17075,MONO,NaN,NaN,MONO-0089,Grassland,2018,2018-05-10 00:00:00,06:35:00,06:46:00,Brian Swimelar,...,False,False,19.0,63.0,Partly Cloudy,Light air movement (1-3 mph) smoke drifts,Slight effect on count,False,Grassland,False
17076,MONO,NaN,NaN,MONO-0089,Grassland,2018,2018-05-10 00:00:00,06:35:00,06:46:00,Brian Swimelar,...,False,False,19.0,63.0,Partly Cloudy,Light air movement (1-3 mph) smoke drifts,Slight effect on count,False,Grassland,False

Data Understanding

In [7]:
df.columns

Index(['Admin_Unit_Code', 'Sub_Unit_Code', 'Site_Name', 'Plot_Name',
       'Location_Type', 'Year', 'Date', 'Start_Time', 'End_Time', 'Observer',
       'Visit', 'Interval_Length', 'ID_Method', 'Distance', 'Flyover_Observed',
       'Sex', 'Common_Name', 'Scientific_Name', 'AcceptedTSN', 'NPSTaxonCode',
       'AOU_Code', 'PIF_Watchlist_Status', 'Regional_Stewardship_Status',
       'Temperature', 'Humidity', 'Sky', 'Wind', 'Disturbance',
       'Initial_Three_Min_Cnt', 'Habitat', 'Previously_Obs'],
      dtype='str')

In [8]:
# check datatype
df.dtypes

Admin_Unit_Code                object
Sub_Unit_Code                  object
Site_Name                         str
Plot_Name                      object
Location_Type                  object
Year                           object
Date                           object
Start_Time                     object
End_Time                       object
Observer                       object
Visit                          object
Interval_Length                object
ID_Method                      object
Distance                       object
Flyover_Observed               object
Sex                            object
Common_Name                    object
Scientific_Name                object
AcceptedTSN                    object
NPSTaxonCode                   object
AOU_Code                       object
PIF_Watchlist_Status           object
Regional_Stewardship_Status    object
Temperature                    object
Humidity                       object
Sky                            object
Wind                           object
Disturbance                    object
Initial_Three_Min_Cnt          object
Habitat                           str
Previously_Obs                 object
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17077 entries, 0 to 17076
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Admin_Unit_Code              17077 non-null  object
 1   Sub_Unit_Code                722 non-null    object
 2   Site_Name                    8546 non-null   str
 3   Plot_Name                    17077 non-null  object
 4   Location_Type                17077 non-null  object
 5   Year                         17077 non-null  object
 6   Date                         17077 non-null  object
 7   Start_Time                   17077 non-null  object
 8   End_Time                     17077 non-null  object
 9   Observer                     17077 non-null  object
 10  Visit                        17077 non-null  object
 11  Interval_Length              17077 non-null  object
 12  ID_Method                    17075 non-null  object
 13  Distance                     15591 non-null  object
 14  Flyover_Observed             17077 non-null  object
 15  Sex                          11894 non-null  object
 16  Common_Name                  17077 non-null  object
 17  Scientific_Name              17077 non-null  object
 18  AcceptedTSN                  17044 non-null  object
 19  NPSTaxonCode                 17075 non-null  object
 20  AOU_Code                     17077 non-null  object
 21  PIF_Watchlist_Status         17077 non-null  object
 22  Regional_Stewardship_Status  17077 non-null  object
 23  Temperature                  17077 non-null  object
 24  Humidity                     17077 non-null  object
 25  Sky                          17077 non-null  object
 26  Wind                         17077 non-null  object
 27  Disturbance                  17077 non-null  object
 28  Initial_Three_Min_Cnt        17077 non-null  object
 29  Habitat                      17077 non-null  str
 30  Previously_Obs               8531 non-null   object
dtypes: object(29), str(2)
memory usage: 4.2+ MB

In [10]:
# Check null value
df.isnull().sum().sort_values(ascending=False)

Sub_Unit_Code                  16355
Previously_Obs                  8546
Site_Name                       8531
Sex                             5183
Distance                        1486
AcceptedTSN                       33
ID_Method                          2
NPSTaxonCode                       2
Year                               0
Start_Time                         0
End_Time                           0
Date                               0
Location_Type                      0
Plot_Name                          0
Admin_Unit_Code                    0
Flyover_Observed                   0
Interval_Length                    0
Observer                           0
Visit                              0
Scientific_Name                    0
AOU_Code                           0
PIF_Watchlist_Status               0
Common_Name                        0
Regional_Stewardship_Status        0
Temperature                        0
Sky                                0
Humidity                           0
Wind                               0
Disturbance                        0
Initial_Three_Min_Cnt              0
Habitat                            0
dtype: int64

In [11]:
df['Sub_Unit_Code'].unique() #missing value = 16355
df['Previously_Obs'].unique() #missing value = 8546
df['Site_Name'].unique() #missing value = 8531
df['AcceptedTSN'].unique() #missing Value = 33

array([179276.0, 178775.0, 178195.0, 179064.0, 178620.0, 179124.0,
       554256.0, 177125.0, 179443.0, 178581.0, 554383.0, 178359.0,
       179731.0, 179150.0, 554138.0, 950039.0, 179801.0, 178259.0,
       179435.0, 179083.0, 178309.0, 179853.0, 178532.0, 179680.0,
       179236.0, 179045.0, 178166.0, 179112.0, 179021.0, 553526.0,
       178339.0, 178262.0, 179009.0, 179492.0, 179333.0, 178448.0,
       179777.0, 179759.0, 178329.0, nan, 177831.0, 179104.0, 179883.0,
       178279.0, 950033.0, 176136.0, 950029.0, 178927.0, 178154.0,
       178979.0, 179788.0, 950009.0, 178844.0, 178850.0, 178541.0,
       950079.0, 178627.0, 178625.0, 178944.0, 950041.0, 179737.0,
       175122.0, 174793.0, 178119.0, 950049.0, 179023.0, 175359.0,
       554382.0, 950010.0, 174999.0, 950042.0, 174773.0, 177921.0,
       178991.0, 950045.0, 179488.0, 174717.0, 179724.0, 175063.0,
       178443.0, 178032.0, 178001.0, 178937.0, 175590.0, 175272.0,
       178964.0, 950011.0, 179637.0, 179628.0, 179410.0, 175265.0,
       175604.0, 179034.0, 179796.0, 950052.0, 950036.0, 950061.0,
       847323.0, 950031.0, 950046.0, 950035.0, 179888.0, 176520.0,
       178277.0, 950106.0, 950097.0, 178186.0, 175350.0, 178431.0,
       175420.0, 179366.0, 175622.0, 179145.0, 175309.0, 177071.0,
       179736.0, 178341, 178464, 179314, 178423, 174861.0, 950040.0,
       179032.0, 178842.0, 179462.0, 178344.0], dtype=object)

In [12]:
# Check duplicate value
df.duplicated().sum()

np.int64(1705)

In [13]:
# check summary
df.describe(include='all').T

,count,unique,top,freq
Admin_Unit_Code,17077,11,ANTI,3921
Sub_Unit_Code,722,8,PISC,257
Site_Name,8546,70,CHOH 1,420
Plot_Name,17077,609,MONO-0054,204
Location_Type,17077,2,Forest,8546
Year,17077,1,2018,17077
Date,17077,64,2018-05-24 00:00:00,743
Start_Time,17077,318,07:23:00,241
End_Time,17077,318,07:33:00,241
Observer,17077,3,Elizabeth Oswald,6391
Visit,17077,3,1,7588
Interval_Length,17077,4,0-2.5 min,8614
ID_Method,17075,3,Singing,9863
Distance,15591,2,50 - 100 Meters,8239
Flyover_Observed,17077,2,False,15591
Sex,11894,3,Undetermined,8410
Common_Name,17077,126,Northern Cardinal,1160
Scientific_Name,17077,127,Cardinalis cardinalis,1160
AcceptedTSN,17044.0,125.0,179124.0,1160.0
NPSTaxonCode,17075,125,94228,1160
AOU_Code,17077,126,NOCA,1160
PIF_Watchlist_Status,17077,2,False,16699
Regional_Stewardship_Status,17077,2,False,13092
Temperature,17077.0,210.0,22.0,437.0
Humidity,17077.0,432.0,70.0,282.0
Sky,17077,5,Partly Cloudy,7145
Wind,17077,4,Light air movement (1-3 mph) smoke drifts,8511
Disturbance,17077,4,No effect on count,8029
Initial_Three_Min_Cnt,17077,2,True,9142
Habitat,17077,2,Forest,8546
Previously_Obs,8531,1,False,8531

Missing Values Handeling

In [14]:
# fill null value with Unknown  
def fill_values(df,columns):
    for col in columns:
        df[col]=df[col].fillna('Unknown')
    return df

df=fill_values(df,['Sex','Distance','Site_Name'])

In [15]:
# sub_unit_code approximately 96% others two are only 2 value are missing so drop it
def drop_col(df, columns):
    df = df.drop(columns=columns)   # no inplace, returns new DataFrame
    return df

df = drop_col(df, ['Sub_Unit_Code', 'ID_Method', 'NPSTaxonCode'])

In [16]:
# fill with average(mode) value
df['AcceptedTSN']=df['AcceptedTSN'].fillna(df['AcceptedTSN'].mode()[0])

Datatype Conversion

In [17]:
df['Date']=pd.to_datetime(df['Date'])
df["Year"] = df["Date"].dt.year

In [18]:
numeric_cols = [
    "Year",
    "Visit",
    "AcceptedTSN",
    "Temperature",
    "Humidity",
    "Initial_Three_Min_Cnt"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [19]:
cat_cols = [
    "Admin_Unit_Code",
    "Site_Name",
    "Plot_Name",
    "Location_Type",
    "Observer",
    "Interval_Length",
    "ID_Method",
    "Distance",
    "Sex",
    "Common_Name",
    "Scientific_Name",
    "AOU_Code",
    "Sky",
    "Wind",
    "Disturbance",
    "Habitat"]

for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype("str")

In [20]:
bool_col=[
    "Regional_Stewardship_Status",
    "PIF_Watchlist_Status",
    "Previously_Obs",
    "Flyover_Observed"]

for col in bool_col:
    if col in df.columns:
        df[col]=df[col].astype("boolean")

Feature engineering

In [21]:
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day

In [22]:
#Season
def season(month):
    if month in [3,4,5]:
        return "Spring"
    elif month in [6,7,8]:
        return "Summer"
    elif month in [9,10,11]:
        return "Autumn"
    else:
        return "Winter"

df["Season"] = df["Month"].apply(season)

In [23]:
from datetime import datetime, date
def add_duration_and_category(df, start_col="Start_Time", end_col="End_Time"):
    df[start_col] = pd.to_datetime(
        df[start_col], format="%H:%M:%S", errors="coerce").dt.time
    df[end_col] = pd.to_datetime(
        df[end_col], format="%H:%M:%S", errors="coerce").dt.time

    def calc_duration(start, end):
        if pd.isna(start) or pd.isna(end):
            return np.nan

        start_dt = datetime.combine(date.today(), start)
        end_dt = datetime.combine(date.today(), end)

        return (end_dt - start_dt).total_seconds() / 60

    df["Observation_Duration_Min"] = [
        calc_duration(start, end)
        for start, end in zip(df[start_col], df[end_col])]

    def categorize_time(t):
        if pd.isna(t):
            return "Unknown"

        hour = t.hour

        if 5 <= hour < 8:
            return "Early Morning"
        elif 8 <= hour < 12:
            return "Morning"
        elif 12 <= hour < 17:
            return "Afternoon"
        elif 17 <= hour < 21:
            return "Evening"
        else:
            return "Night"
    df["Time_of_Day"] = df[start_col].apply(categorize_time)
    return df

df = add_duration_and_category(df)

In [24]:
df["Conservation_Priority"] = (
    df["PIF_Watchlist_Status"].astype(str)
    + " / "
    + df["Regional_Stewardship_Status"].astype(str))

EDA

In [25]:
#Analysis 1 — Habitat comparison
df.groupby("Location_Type")["Scientific_Name"].nunique()

Location_Type
Forest       108
Grassland    107
Name: Scientific_Name, dtype: int64

In [26]:
#Analysis 2 — Total observations by habitat
df["Location_Type"].value_counts()

Location_Type
Forest       8546
Grassland    8531
Name: count, dtype: int64

In [27]:
#Analysis 3 — Biodiversity by administrative unit
species_admin = (
    df.groupby("Admin_Unit_Code")["Scientific_Name"].nunique().sort_values(ascending=False))

In [28]:
#Analysis 4 — Biodiversity by plot
plot_diversity = (
    df.groupby("Plot_Name")["Scientific_Name"].nunique().sort_values(ascending=False))

In [29]:
#Analysis 5 — Most frequently observed species
df["Common_Name"].value_counts().head(10)

Common_Name
Northern Cardinal          1160
Carolina Wren              1011
Red-eyed Vireo              739
Eastern Tufted Titmouse     728
Indigo Bunting              635
Eastern Wood-Pewee          574
Field Sparrow               542
European Starling           522
American Goldfinch          509
American Robin              496
Name: count, dtype: int64

In [30]:
#Analysis 6 — Species habitat preference
species_habitat = pd.crosstab(df["Common_Name"],df["Location_Type"])
species_habitat

Location_Type            Forest  Grassland
Common_Name
Acadian Flycatcher          436         26
American Crow               142        159
American Goldfinch          147        362
American Kestrel              0          8
American Redstart            25          7
...                         ...        ...
Yellow-billed Cuckoo        133         43
Yellow-breasted Chat          4          5
Yellow-rumped Warbler         3          0
Yellow-throated Vireo        55          3
Yellow-throated Warbler       3          0

[126 rows x 2 columns]

In [31]:
#Analysis 7 — Monthly bird activity
monthly = df.groupby("Month_Name").size()
monthly

Month_Name
July    4885
June    6596
May     5596
dtype: int64

In [32]:
#Analysis 8 — Seasonal biodiversity
season_diversity = (df.groupby("Season")["Scientific_Name"].nunique())
season_diversity

Season
Spring    114
Summer    107
Name: Scientific_Name, dtype: int64

In [33]:
# Analysis 9 — Identification method
if "ID_Method" not in df.columns:
    df["ID_Method"] = pd.concat(
        [forest["ID_Method"], grassland["ID_Method"]],
        ignore_index=True)

df["ID_Method"].fillna("Unknown").value_counts()

ID_Method
Singing          9863
Calling          4061
Visualization    3151
Unknown             2
Name: count, dtype: int64

In [34]:
#Analysis 10 — Sex ratio
pd.crosstab(df["Common_Name"],df["Sex"])

Sex                      Female  Male  Undetermined  Unknown
Common_Name
Acadian Flycatcher            0     0            26      436
American Crow                 0     0           159      142
American Goldfinch           21    57           302      129
American Kestrel              0     0             8        0
American Redstart             0     8            20        4
...                         ...   ...           ...      ...
Yellow-billed Cuckoo          0     0            44      132
Yellow-breasted Chat          0     0             5        4
Yellow-rumped Warbler         0     0             2        1
Yellow-throated Vireo         0     3            55        0
Yellow-throated Warbler       0     0             3        0

[126 rows x 4 columns]

Environmental analysis

In [35]:
#Temperature
temp_analysis = (df.groupby("Temperature").size().reset_index(name="Observations"))

In [36]:
#Humidity
df.groupby("Humidity")["Scientific_Name"].nunique()

Humidity
7.300000      8
9.500000     17
13.300000    14
17.500000    11
32.900002    12
             ..
94.400002     9
94.599998     9
95.099998     8
97.900002    12
98.800003    11
Name: Scientific_Name, Length: 432, dtype: int64

In [37]:
#Sky condition
df.groupby("Sky").agg(
    Observations=("Scientific_Name","size"),
    Species_Richness=("Scientific_Name","nunique"))

                     Observations  Species_Richness
Sky
Clear or Few Clouds          5809               110
Cloudy/Overcast              3097                99
Fog                           647                62
Mist/Drizzle                  379                57
Partly Cloudy                7145               112

In [38]:
#Wind
wind_analysis = (
    df.groupby("Wind", observed=True)
      .agg(
          Total_Observations=("Scientific_Name", "size"),
          Unique_Species=("Scientific_Name", "nunique"))
      .reset_index()
      .sort_values("Total_Observations", ascending=False))

wind_analysis

,Wind,Total_Observations,Unique_Species
2,Light air movement (1-3 mph) smoke drifts,8511,116
0,Calm (< 1 mph) smoke rises vertically,4417,100
3,Light breeze (4-7 mph) wind felt on face,3737,105
1,"Gentle breeze (8-12 mph), leaves in motion",412,68

In [39]:
#Disturbance
df.groupby("Disturbance").agg(
    Observations=("Scientific_Name","size"),
    Unique_Species=("Scientific_Name","nunique"))

                          Observations  Unique_Species
Disturbance
Moderate effect on count          1819              90
No effect on count                8029             108
Serious effect on count            479              62
Slight effect on count            6750             110

In [40]:
#Conservation analysis
watchlist = df[ df["PIF_Watchlist_Status"] == True]
watchlist

,Admin_Unit_Code,Site_Name,Plot_Name,Location_Type,Year,Date,Start_Time,End_Time,Observer,Visit,...,Habitat,Previously_Obs,Month,Month_Name,Day,Season,Observation_Duration_Min,Time_of_Day,Conservation_Priority,ID_Method
127,ANTI,ANTI 2,ANTI-0206,Forest,2018,2018-05-24,10:10:00,10:20:00,Brian Swimelar,1,...,Forest,<NA>,5,May,24,Spring,10.0,Morning,True / True,Singing
146,ANTI,ANTI 2,ANTI-0207,Forest,2018,2018-05-24,10:27:00,10:37:00,Brian Swimelar,1,...,Forest,<NA>,5,May,24,Spring,10.0,Morning,True / True,Singing
193,ANTI,ANTI 1,ANTI-0072,Forest,2018,2018-06-26,06:12:00,06:22:00,Kimberly Serno,2,...,Forest,<NA>,6,June,26,Summer,10.0,Early Morning,True / True,Singing
222,ANTI,ANTI 1,ANTI-0052,Forest,2018,2018-06-26,05:31:00,05:41:00,Kimberly Serno,2,...,Forest,<NA>,6,June,26,Summer,10.0,Early Morning,True / True,Singing
236,ANTI,ANTI 2,ANTI-0194,Forest,2018,2018-06-26,10:31:00,10:41:00,Elizabeth Oswald,2,...,Forest,<NA>,6,June,26,Summer,10.0,Morning,True / True,Singing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15006,MONO,Unknown,MONO-0033,Grassland,2018,2018-06-05,08:10:00,08:21:00,Brian Swimelar,2,...,Grassland,False,6,June,5,Summer,11.0,Morning,True / True,Singing
15278,MONO,Unknown,MONO-0050,Grassland,2018,2018-06-14,09:17:00,09:27:00,Kimberly Serno,2,...,Grassland,False,6,June,14,Summer,10.0,Morning,True / True,Singing
15355,MONO,Unknown,MONO-0057,Grassland,2018,2018-06-14,07:06:00,07:16:00,Kimberly Serno,2,...,Grassland,False,6,June,14,Summer,10.0,Early Morning,True / True,Singing
16654,MONO,Unknown,MONO-0076,Grassland,2018,2018-05-10,09:15:00,09:25:00,Elizabeth Oswald,1,...,Grassland,False,5,May,10,Spring,10.0,Morning,True / True,Singing
16845,MONO,Unknown,MONO-0076,Grassland,2018,2018-07-13,08:22:00,08:32:00,Brian Swimelar,3,...,Grassland,False,7,July,13,Summer,10.0,Morning,True / True,Singing

In [41]:
#Observer bias
observer_stats = df.groupby("Observer").agg(
    Observations=("Scientific_Name","size"),
    Unique_Species=("Scientific_Name","nunique"),
    Plots=("Plot_Name","nunique"))

In [42]:
def shannon_index(group):
    counts = group["Scientific_Name"].value_counts()
    proportions = counts / counts.sum()
    return -(proportions * np.log(proportions)).sum()

shannon = (
    df.groupby("Habitat")
      .apply(shannon_index)
      .reset_index(name="Shannon_Index"))

shannon

     Habitat  Shannon_Index
0     Forest       3.577995
1  Grassland       3.703715

In [43]:
#Habitat preference analysis
habitat_pref = pd.crosstab(
    df["Common_Name"],
    df["Habitat"])

habitat_pref["Total"] = habitat_pref.sum(axis=1)

habitat_pref["Forest_Pct"] = (
    habitat_pref.get("Forest", 0) /
    habitat_pref["Total"] * 100)

habitat_pref["Grassland_Pct"] = (
    habitat_pref.get("Grassland", 0) /
    habitat_pref["Total"] * 100)

habitat_pref.head()

Habitat             Forest  Grassland  Total  Forest_Pct  Grassland_Pct
Common_Name
Acadian Flycatcher     436         26    462   94.372294       5.627706
American Crow          142        159    301   47.176080      52.823920
American Goldfinch     147        362    509   28.880157      71.119843
American Kestrel         0          8      8    0.000000     100.000000
American Redstart       25          7     32   78.125000      21.875000

In [44]:
def preference(row):
    if row["Forest_Pct"] >= 70:
        return "Forest Preferred"
    elif row["Grassland_Pct"] >= 70:
        return "Grassland Preferred"
    else:
        return "Mixed Habitat"

habitat_pref["Habitat_Preference"] = habitat_pref.apply(preference,axis=1)

In [45]:
numeric_env = [
    "Temperature",
    "Humidity",
    "Visit",
    "Initial_Three_Min_Cnt"]

corr = df[numeric_env].corr()
corr.style.background_gradient()

In [46]:
df[
    ["Temperature", "Humidity", "Initial_Three_Min_Cnt"]
].describe()

        Temperature      Humidity
count  17077.000000  17077.000000
mean      22.570399     73.692112
std        4.263851     12.328380
min       11.000000      7.300000
25%       19.700001     67.500000
50%       22.299999     75.800003
75%       25.200001     83.000000
max       37.299999     98.800003

In [47]:
habitat_summary = (
    df.groupby("Habitat")
      .agg(
          Total_Observations=("Scientific_Name", "size"),
          Unique_Species=("Scientific_Name", "nunique"),
          Unique_Plots=("Plot_Name", "nunique"),
          Avg_Temperature=("Temperature", "mean"),
          Avg_Humidity=("Humidity", "mean")).reset_index())

habitat_summary

,Habitat,Total_Observations,Unique_Species,Unique_Plots,Avg_Temperature,Avg_Humidity
0,Forest,8546,108,408,21.871507,77.757032
1,Grassland,8531,107,201,23.270519,69.620045

In [48]:
admin_summary = (
    df.groupby("Admin_Unit_Code")
      .agg(
          Total_Observations=("Scientific_Name", "size"),
          Unique_Species=("Scientific_Name", "nunique"),
          Unique_Plots=("Plot_Name", "nunique")).reset_index().sort_values("Unique_Species",
          ascending=False))

admin_summary.head()

  Admin_Unit_Code  Total_Observations  Unique_Species  Unique_Plots
6            MONO                3385             100            83
5            MANA                2276              81            68
0            ANTI                3921              81            99
2            CHOH                2202              80            90
7            NACE                 684              66            29

Export cleaned dataset

In [ ]:
df.to_csv(r"Bird_Observation_Cleaned.csv",index=False)